resize stimuli "on screen" to model's declared visual degrees (#153)
* resize stimuli based on model's declared visual degrees

* do not convert stimulus_set if target==source

* set visual_degrees to assembly for unit test

* add visual_degrees again

* set screen degrees for Rajalingham and tolias.Cadena (#197)

* Corrected stimulus size of 8deg for behavioral benchmark.
Removes cropping images to 85% for tensorflow models in preprocessing.
Adds stimilus size of 2deg for Cadena benchmark.
Allows behavior benchmark to work on models with multiple layers.

* Added V1 neural predictivity benchmark for the Movshon public dataset and for the Tolias dataset

* use logging for Score warnings; add comments; quick-return nan for ost no timebins

* fix tests for V1/2 aperture; download precomputed test files from S3

https://github.com/brain-score/brainio_collection/pull/27

* fix lstrip_local: use name instead of fixed index

* fix PrecomputedProbabilities for Rajalingham2018 tests: add visual degrees

* fix test file download, add echo statement

* require numpy>=1.16 following https://github.com/scikit-image/scikit-image/issues/3655#issuecomment-484382609

* fix previous commit: need at least 1.16

* fix Kar2019ost test and add precomputed test; remove mask-benchmark test

* use 3.6 again in an attempt to fix mysterious curl pull issue

(in travis' `pip install .`)
Collecting brainio_collection@ git+https://github.com/brain-score/brainio_collection
  Cloning https://github.com/brain-score/brainio_collection to /tmp/pip-install-7suake0n/brainio-collection
  Running command git clone -q https://github.com/brain-score/brainio_collection /tmp/pip-install-7suake0n/brainio-collection
  error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed

* Add visual degrees to benchmarks; add V1 single benchmark (#199)

* Adds stimulus size of 6deg for behavioral benchmark.
Adds stimilus size of 2deg for Cadena benchmark.
Allows behavior benchmark to work on models with multiple layers.

* Corrected stimulus size of 8deg for behavioral benchmark.
Removes cropping images to 85% for tensorflow models in preprocessing.
Adds stimilus size of 2deg for Cadena benchmark.
Allows behavior benchmark to work on models with multiple layers.

* Added V1 neural predictivity benchmark for the Movshon public dataset and for the Tolias dataset

* Corrected several bugs to run visual degrees
Moved visual degrees implementation from stimulus set to benchmarks
Added single neuron mapping

* Added V1 neural predictivity benchmark for the Movshon public dataset and for the Tolias dataset

* Corrected screen degrees transformation

* fix PR comments: CamelCase naming, public benchmarks, correlations r

Co-authored-by: Martin Schrimpf <m4rtinsch@gmail.com>

* test for the correct ratio of gray in stimuli of benchmarks in response to different-sized candidates

* update comment

* remove out-dated global setting of stimulus set degrees

* add visual degrees to public benchmarks

* place stimuli on screen according to visual degrees for example benchmark

Co-authored-by: tiagogmarques <tmarques@mit.edu>